language: go

go:
  - "1.15"

services:
  - docker

script:
  - make 

after_success:
  - echo "$QUAY_BOT_PASSWORD" | docker login --username "$QUAY_BOT_USERNAME" --password-stdin quay.io
  - make docker-build
  - make docker-build

notifications:
    email:
      recipients:
        - ashokponkumar@in.ibm.com
      on_success: never 
      on_failure: always
