# permissions for end users to edit move2kubes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: move2kube-editor-role
rules:
- apiGroups:
  - charts.io
  resources:
  - move2kubes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.io
  resources:
  - move2kubes/status
  verbs:
  - get
