apiVersion: konveyor.io/v1alpha1
kind: Move2Kube
metadata:
  name: move2kube-sample
spec:
  # Default values copied from <project_dir>/helm-charts/move2kube/values.yaml
  deployment:
    api:
      replicas: 1
      privilegedPods: false
      imageTag: ""
      memory: "1Gi"
      cpu: "300m"
    authServer:
      enable: false
      replicas: 1
      memory: "1Gi"
      cpu: "300m"
    database:
      enable: false
      replicas: 1
      startEmpty: true
      memory: "1Gi"
      cpu: "300m"
  ingress:
    enable: true
    preferRoute: false
    host: mydomain.com
    tlsSecretName: myTLSSecret
  persistentVolumeClaim:
    enable: false
    createNew: true
    name: ""
    storageClassName: ""
    storageSize: 1Gi
  secret:
    api:
      enable: false
      createNew: true
      name: ""
      configYAML: ""
    authServer:
      createNew: true
      name: ""
      adminUsername: admin
      adminPassword: password
      databaseUsername: auth-server
      databasePassword: password
      realmJSON: ""
      standaloneHAXML: ""
  securityContextContraints:
    enable: false
  serviceAccount:
    enable: false
    createNew: true
    name: ""
