apiVersion: v1
kind: Service
metadata:
  labels:
    io.move2kube.service: {{ .Release.Name }}-move2kubeapi
  name: {{ .Release.Name }}-move2kubeapi
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.move2kube.service: {{ .Release.Name }}-move2kubeapi
  type: ClusterIP
status:
  loadBalancer: {}
