apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeui
  name: {{ .Release.Name }}-move2kubeui
spec:
  {{ if .Values.ingresstls }}
  tls:
    - hosts:
        - {{ .Release.Name }}-{{ .Release.Namespace }}.{{.Values.ingresshost}}
      secretName: {{ .Values.ingresstls }}
  {{ end }}
  rules:
    - host: {{ .Release.Name }}-{{ .Release.Namespace }}.{{.Values.ingresshost}}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-move2kubeui
              servicePort: 8080
            path: /
status:
  loadBalancer: {}
