apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeapi
  name: {{ .Release.Name }}-move2kubeapi
spec:
  replicas: 2
  selector:
    matchLabels:
      move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeapi
  serviceName: {{ .Release.Name }}-move2kubeapiheadless
  template:
    metadata:
      labels:
        move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeapi
      name: {{ .Release.Name }}-move2kubeapi
    spec:
      serviceAccountName: {{ .Release.Name }}-move2kube
      containers:
        - image: quay.io/konveyor/move2kube-api:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: Always
          name: move2kubeapi
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            privileged: true
          resources: {}
          volumeMounts:
            - mountPath: /workspace
              name: {{ .Release.Name }}-data-pvcclaim1
            - mountPath: /var/lib/containers
              name: container-storage
      initContainers:
        - name: initcontainer 
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - chown -R 1000:1000 /workspace; 
          volumeMounts:
          - name: {{ .Release.Name }}-data-pvcclaim1
            mountPath: /workspace
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-data-pvcclaim1
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-pvcclaim1
        - name: container-storage
          emptyDir: {}
