apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeui
  name: {{ .Release.Name }}-move2kubeui
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-move2kubeui
              servicePort: 8080
            path: /{{ .Release.Name }}(/|$)(.*)
status:
  loadBalancer: {}
