apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-move2kubeapi
spec:
  accessModes:
  {{- if gt (.Values.api.replicas | int) 1 }}
    - ReadWriteMany
  {{- else }}
    - ReadWriteOnce
  {{- end }}
  storageClassName: {{ .Values.storageclass }}
  resources:
    requests:
      storage: {{ .Values.storagesize }}
