apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-move2kubeui"
  labels:
    move2kube.konveyor.io/service: "{{ .Release.Name }}-move2kubeui"
  annotations:
    move2kube.service.expose: "true"
spec:
  type: ClusterIP
  ports:
    - name: "port-8080"
      port: 8080
      targetPort: 8080
  selector:
    move2kube.konveyor.io/service: "{{ .Release.Name }}-move2kubeui"
