apiVersion: v1
kind: Service
metadata:
  annotations:
    move2kube.service.expose: "true"
  labels:
    move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeui
  name: {{ .Release.Name }}-move2kubeui
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeui
  type: ClusterIP
status:
  loadBalancer: {}
