{{- if and (.Values.ingress.enable) (not .Values.ingress.preferRoute) }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-move2kubeui"
  labels:
    move2kube.konveyor.io/service: "{{ .Release.Name }}-move2kubeui"
spec:
  {{- if .Values.ingress.tlsSecret }}
  tls:
    - hosts:
        - "{{ .Release.Name }}-{{ .Release.Namespace }}.{{ .Values.ingress.domainName }}"
      secretName: "{{ .Values.ingress.tlsSecret }}"
  {{- end }}
  rules:
    - host: "{{ .Release.Name }}-{{ .Release.Namespace }}.{{ .Values.ingress.domainName }}"
      http:
        paths:
          - path: /
            {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-move2kubeui"
                port:
                  number: 8080
            {{- else }}
            backend:
              serviceName: "{{ .Release.Name }}-move2kubeui"
              servicePort: 8080
            {{- end }}
{{- end }}
