apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-move2kubeui"
  labels:
    move2kube.konveyor.io/service: "{{ .Release.Name }}-move2kubeui"
  annotations:
    move2kube.konveyor.io/expose: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      move2kube.konveyor.io/service: "{{ .Release.Name }}-move2kubeui"
  template:
    metadata:
      name: "{{ .Release.Name }}-move2kubeui"
      labels:
        move2kube.konveyor.io/service: "{{ .Release.Name }}-move2kubeui"
      annotations:
        move2kube.konveyor.io/expose: "true"
    spec:
      {{- if .Values.serviceAccount.enable }}
      serviceAccountName: '{{ .Values.serviceAccount.name | default (print .Release.Name "-move2kube") }}'
      {{- end }}
      containers:
        - name: move2kubeui
          image: "quay.io/konveyor/move2kube-ui:{{ .Values.deployment.ui.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          {{- if .Values.secret.enable }}
          command: ["node", "server.js", "--auth", "secrets/auth.json"]
          {{- else }}
          command: ["node", "server.js"]
          {{- end }}
          env:
            - name: MOVE2KUBEAPI
              value: http://{{ .Release.Name }}-move2kubeapi:8080
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: common-volume
              mountPath: /app/common
            {{- if .Values.secret.enable }}
            - name: secrets-volume
              mountPath: /app/secrets
              readOnly: true
            {{- end }}
      initContainers:
        - name: initcontainer
          image: quay.io/konveyor/busybox
          command: ["/bin/sh", "-c"]
          args:
            - chmod -R a+rwx /app/common;
          volumeMounts:
          - name: common-volume
            mountPath: /app/common
      restartPolicy: Always
      volumes:
        - name: common-volume
          emptyDir: {}
        {{- if .Values.secret.enable }}
        - name: secrets-volume
          secret:
            secretName: '{{ .Values.secret.name | default (print .Release.Name "-move2kubeui") }}'
        {{- end }}
