name: Release

on: create

jobs:
  image_build:
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - id: only_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
      - uses: actions/checkout@v2
      - name: build
        run: |
          VERSION=${{ steps.only_tag.outputs.tag }} make docker-build
          VERSION=${{ steps.only_tag.outputs.tag }} make bundle-build
      - name: Push images to quay
        run: |
          echo "${{ secrets.QUAY_BOT_PASSWORD }}" | docker login --username "${{ secrets.QUAY_BOT_USERNAME }}" --password-stdin quay.io
          VERSION=${{ steps.only_tag.outputs.tag }} make docker-push
          docker push quay.io/konveyor/move2kube-bundle:${{ steps.only_tag.outputs.tag }}
      - name: success slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Built and pushed quay.io/konveyor/move2kube-operator:${{ steps.only_tag.outputs.tag }}"
          SLACK_TITLE: Success
          SLACK_USERNAME: GitHubActions
      - if: failure()
        name: failure slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#BD3232"
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Failed to build and push image quay.io/konveyor/move2kube-operator:${{ steps.only_tag.outputs.tag }}"
          SLACK_TITLE: Failed
          SLACK_USERNAME: GitHubActions

  create_release_draft:
    needs: [image_build]
    name: Create release draft
    runs-on: ubuntu-latest
    steps:
      - id: only_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: create release draft
        run: |
          npm install github-release-notes@v0.17.3 -g
          gren release --draft --prerelease --tags ${{ steps.only_tag.outputs.tag }} --username=${{ github.repository_owner }} --repo=${{ github.event.repository.name }} --token=${{ secrets.GITHUB_TOKEN }}
      - name: slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Release draft for move2kube-operator ${{ steps.only_tag.outputs.tag }} created: https://github.com/konveyor/move2kube-operator/releases"
          SLACK_TITLE: Success
          SLACK_USERNAME: GitHubActions
